
import { Camera, Lens, Scenario } from './types';

export const CAMERAS: Camera[] = [
  { id: 'c1', brand: 'Canon', model: 'EOS Rebel T7 / 2000D', maxIso: 6400 },
  { id: 'c2', brand: 'Canon', model: 'EOS Rebel T8i / 850D', maxIso: 25600 },
  { id: 'c3', brand: 'Canon', model: 'EOS Rebel SL3 / 250D', maxIso: 25600 },
  { id: 'c4', brand: 'Canon', model: 'EOS M50 Mark II', maxIso: 25600 },
  { id: 'c5', brand: 'Canon', model: 'EOS R50', maxIso: 32000 },
  { id: 'c6', brand: 'Canon', model: 'EOS RP', maxIso: 40000 },
  { id: 'c7', brand: 'Nikon', model: 'D3500', maxIso: 25600 },
  { id: 'c8', brand: 'Nikon', model: 'D5600', maxIso: 25600 },
  { id: 'c9', brand: 'Nikon', model: 'D7500', maxIso: 51200 },
  { id: 'c10', brand: 'Nikon', model: 'Z50', maxIso: 51200 },
  { id: 'c11', brand: 'Nikon', model: 'Z5', maxIso: 51200 },
  { id: 'c12', brand: 'Nikon', model: 'Z fc', maxIso: 51200 },
  { id: 'c13', brand: 'Sony', model: 'Alpha A6000', maxIso: 25600 },
  { id: 'c14', brand: 'Sony', model: 'Alpha A6100', maxIso: 32000 },
  { id: 'c15', brand: 'Sony', model: 'Alpha A6400', maxIso: 32000 },
  { id: 'c16', brand: 'Sony', model: 'ZV-E10', maxIso: 32000 },
  { id: 'c17', brand: 'Sony', model: 'Alpha 7 III', maxIso: 51200 },
  { id: 'c18', brand: 'Sony', model: 'Alpha 7C', maxIso: 51200 },
  { id: 'c19', brand: 'Fujifilm', model: 'X-T30', maxIso: 12800 },
  { id: 'c20', brand: 'Fujifilm', model: 'X-T200', maxIso: 12800 },
  { id: 'c21', brand: 'Fujifilm', model: 'X-S10', maxIso: 12800 },
  { id: 'c22', brand: 'Fujifilm', model: 'X-E4', maxIso: 12800 },
  { id: 'c23', brand: 'Olympus', model: 'OM-D E-M10 Mark IV', maxIso: 25600 },
  { id: 'c24', brand: 'Olympus', model: 'PEN E-PL10', maxIso: 25600 },
  { id: 'c25', brand: 'Panasonic', model: 'Lumix G7', maxIso: 25600 },
  { id: 'c26', brand: 'Panasonic', model: 'Lumix GX85', maxIso: 25600 },
  { id: 'c27', brand: 'Panasonic', model: 'Lumix G100', maxIso: 25600 },
  { id: 'c28', brand: 'Pentax', model: 'K-70', maxIso: 102400 },
  { id: 'c29', brand: 'Leica', model: 'CL', maxIso: 50000 },
  { id: 'c30', brand: 'Hasselblad', model: 'X1D II', maxIso: 25600 },
];

export const LENSES: Lens[] = [
  { id: 'l1', name: '18-55mm f/3.5-5.6 (Kit)', maxAperture: 3.5, isZoom: true },
  { id: 'l2', name: '24-70mm f/2.8', maxAperture: 2.8, isZoom: true },
  { id: 'l3', name: '24-105mm f/4', maxAperture: 4.0, isZoom: true },
  { id: 'l4', name: '18-135mm f/3.5-5.6', maxAperture: 3.5, isZoom: true },
  { id: 'l5', name: '16-80mm f/2.8-4', maxAperture: 2.8, isZoom: true },
  { id: 'l6', name: '55-200mm f/4-5.6', maxAperture: 4.0, isZoom: true },
  { id: 'l7', name: '70-200mm f/2.8', maxAperture: 2.8, isZoom: true },
  { id: 'l8', name: '70-300mm f/4-5.6', maxAperture: 4.0, isZoom: true },
  { id: 'l9', name: '10-18mm f/4.5-5.6', maxAperture: 4.5, isZoom: true },
  { id: 'l10', name: '16-35mm f/4', maxAperture: 4.0, isZoom: true },
  { id: 'l11', name: '14mm f/2.8 (Fixa)', maxAperture: 2.8, isZoom: false },
  { id: 'l12', name: '35mm f/1.8 (Fixa)', maxAperture: 1.8, isZoom: false },
  { id: 'l13', name: '50mm f/1.8 (Fixa)', maxAperture: 1.8, isZoom: false },
  { id: 'l14', name: '50mm f/1.4 (Fixa)', maxAperture: 1.4, isZoom: false },
  { id: 'l15', name: '85mm f/1.8 (Fixa)', maxAperture: 1.8, isZoom: false },
  { id: 'l16', name: '24mm f/2.8 (Fixa)', maxAperture: 2.8, isZoom: false },
  { id: 'l17', name: '60mm f/2.8 Macro', maxAperture: 2.8, isZoom: false },
  { id: 'l18', name: '100mm f/2.8 Macro', maxAperture: 2.8, isZoom: false },
  { id: 'l19', name: '40mm f/2.8 Pancake', maxAperture: 2.8, isZoom: false },
  { id: 'l20', name: '18-200mm f/3.5-6.3', maxAperture: 3.5, isZoom: true },
];

export const SCENARIOS: Scenario[] = [
  { id: 's1', name: 'Retrato em Estúdio', icon: '📸', description: 'Ambiente controlado com luz artificial.' },
  { id: 's2', name: 'Retrato ao Ar Livre', icon: '☀️', description: 'Luz natural, foco no desfoque de fundo.' },
  { id: 's3', name: 'Paisagem Natural', icon: '🏔️', description: 'Montanhas e florestas, foco em nitidez total.' },
  { id: 's4', name: 'Paisagem Urbana', icon: '🏙️', description: 'Arquitetura e ruas, capturando o espírito da cidade.' },
  { id: 's5', name: 'Fotografia Noturna (Cidade)', icon: '🌃', description: 'Luzes artificiais e pouca luz ambiente.' },
  { id: 's6', name: 'Fotografia Noturna (Astros)', icon: '🌌', description: 'Estrelas e Via Láctea, exige longa exposição.' },
  { id: 's7', name: 'Eventos', icon: '🥂', description: 'Casamentos e festas, momentos rápidos e variados.' },
  { id: 's8', name: 'Produtos', icon: '🎁', description: 'Still life, detalhes e fidelidade de cores.' },
  { id: 's9', name: 'Macro', icon: '🦋', description: 'Close-ups extremos de pequenos objetos ou natureza.' },
  { id: 's10', name: 'Animais', icon: '🐾', description: 'Pets em movimento, exige foco rápido.' },
  { id: 's11', name: 'Esportes/Ação', icon: '⚽', description: 'Movimentos rápidos, exige alta velocidade de obturador.' },
  { id: 's12', name: 'Comida', icon: '🍕', description: 'Texturas e cores apetitosas.' },
  { id: 's13', name: 'Golden Hour', icon: '🌅', description: 'Luz quente e suave do nascer ou pôr do sol.' },
  { id: 's14', name: 'Interior Pouca Luz', icon: '🏠', description: 'Museus ou casas sem flash permitido.' },
  { id: 's15', name: 'Crianças/Bebês', icon: '👶', description: 'Momentos espontâneos e rápidos.' },
];

export const GLOSSARY = [
  { term: 'ISO', description: 'Sensibilidade do sensor à luz. Valores baixos (100) para muita luz, valores altos (3200+) para pouca luz, mas geram ruído.' },
  { term: 'Abertura (f/stop)', description: 'O quão aberto está o diafragma da lente. Números menores (f/1.8) deixam entrar mais luz e desfocam o fundo.' },
  { term: 'Velocidade do Obturador', description: 'O tempo que o sensor fica exposto. Velocidades rápidas (1/1000) congelam movimento, lentas (1/30) podem borrar.' },
  { term: 'Balanço de Branco (WB)', description: 'Ajuste de cor para garantir que o branco pareça branco sob diferentes tipos de luz.' },
  { term: 'Profundidade de Campo', description: 'A zona de nitidez da foto. Controlada principalmente pela abertura.' },
  { term: 'Foco (AF-S / AF-C)', description: 'AF-S para objetos parados, AF-C para objetos em movimento que a câmera deve seguir.' }
];
